/**
 * Voter authentication.
 *
 * These tests cover the properties a verification code and a session have to have
 * for the system to be worth anything: a code is generated by the server, never
 * stored, expires, is single use, tolerates a bounded number of wrong guesses and
 * then locks; a session is minted server side, is only as good as its cookie,
 * expires absolutely and idles out, and can be revoked.
 *
 * They run against a real in-memory database rather than a mock, because the
 * behaviour under test *is* the SQL — an attempt counter that is not persisted is
 * not an attempt counter.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { createHmac } from 'node:crypto'
import initSqlJs from 'sql.js'
import { queryOne, queryScalar, text, type SqlDatabase } from './db'
import { DEFAULT_CHALLENGE_POLICY, type ChallengePolicy } from './otp'
import {
  activeChallenges,
  codesMatch,
  consumeChallenge,
  findLiveChallenge,
  generateCode,
  isLive,
  issueChallenge,
  pruneChallenges,
  verifyChallenge,
} from './otp'
import {
  VOTER_SESSION_IDLE_MS,
  createSession,
  resolveSession,
  revokeForVoter,
  revokeToken,
  serializeSessionCookie,
  clearSessionCookie,
} from './voterSession'

const T0 = Date.UTC(2026, 0, 1, 12, 0, 0)
const ELECTION = 'E-1'

let database: SqlDatabase

/**
 * The subset of the schema these modules touch. Kept local so the tests do not
 * depend on the production schema string, which would make a schema change look
 * like a test failure.
 */
const SCHEMA = `
CREATE TABLE voter_challenges (
  id TEXT PRIMARY KEY, election_id TEXT NOT NULL, voter_record_id INTEGER NOT NULL,
  channel TEXT NOT NULL, code_hash TEXT NOT NULL, salt TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL,
  created_at TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT, locked_until TEXT
);
CREATE TABLE voter_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, token_hash TEXT NOT NULL UNIQUE,
  election_id TEXT NOT NULL, voter_record_id INTEGER NOT NULL,
  created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, expires_at TEXT NOT NULL,
  ip TEXT, user_agent TEXT, revoked_at TEXT, revoked_reason TEXT
);
CREATE TABLE security_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT, request_id TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL, severity TEXT NOT NULL, admin_id INTEGER, admin_label TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '{}', ip TEXT,
  acknowledged INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL
);
CREATE TABLE voters (id INTEGER PRIMARY KEY, full_name TEXT NOT NULL);
`

beforeEach(async () => {
  const SQL = await initSqlJs()
  database = new SQL.Database() as unknown as SqlDatabase
  database.run(SCHEMA)
})

afterEach(() => {
  database.close()
})

function policy(overrides: Partial<ChallengePolicy> = {}): ChallengePolicy {
  return { ...DEFAULT_CHALLENGE_POLICY, ...overrides }
}

function issue(now = T0, overrides: Partial<ChallengePolicy> = {}) {
  return issueChallenge(database, {
    electionId: ELECTION,
    voterRecordId: 42,
    channel: 'phone',
    destination: '5550100',
    policy: policy(overrides),
    now,
  })
}

/* ------------------------------------------------------------- generation --- */

describe('code generation', () => {
  it('produces a numeric code of the requested length', () => {
    for (const digits of [4, 6, 8, 10]) {
      const code = generateCode(digits)
      expect(code).toHaveLength(digits)
      expect(code).toMatch(/^\d+$/)
    }
  })

  it('zero pads rather than shortening', () => {
    // `randomInt` can return a small number; a code must always be the full
    // length so the field width and the comparison agree.
    for (let attempt = 0; attempt < 200; attempt += 1) {
      expect(generateCode(6)).toHaveLength(6)
    }
  })

  it('does not repeat itself, so a collision cannot be mistaken for a replay', () => {
    const seen = new Set<string>()
    for (let attempt = 0; attempt < 500; attempt += 1) seen.add(generateCode(8))
    expect(seen.size).toBe(500)
  })

  it('clamps an absurd length rather than throwing', () => {
    expect(generateCode(0)).toHaveLength(4)
    expect(generateCode(99)).toHaveLength(10)
  })
})

/* ---------------------------------------------------------------- storage --- */

describe('storage of a code', () => {
  it('never writes the code to the database', () => {
    const issued = issue()
    expect(issued.ok).toBe(true)
    if (!issued.ok) return

    const row = queryOne(database, 'SELECT * FROM voter_challenges WHERE id = ?', [issued.challenge.id])
    const serialised = JSON.stringify(row)
    expect(serialised).not.toContain(issued.code)
    expect(text(row?.code_hash)).not.toBe(issued.code)
  })

  it('uses a distinct salt per challenge, so identical codes hash differently', () => {
    const first = issue(T0, { resendCooldownSeconds: 0 })
    const second = issue(T0 + 1000, { resendCooldownSeconds: 0 })
    if (!first.ok || !second.ok) throw new Error('expected both to be issued')
    const a = queryOne(database, 'SELECT salt, code_hash FROM voter_challenges WHERE id = ?', [first.challenge.id])
    const b = queryOne(database, 'SELECT salt, code_hash FROM voter_challenges WHERE id = ?', [second.challenge.id])
    expect(text(a?.salt)).not.toBe(text(b?.salt))
  })

  it('treats a leading zero as part of the code', () => {
    // `000123` and `123` are different strings and must not compare equal, or a
    // code could be shortened by one character and still be accepted.
    const stored = hashForTest('salt', '000123')
    expect(codesMatch('salt', stored, '123')).toBe(false)
    expect(codesMatch('salt', stored, '000123')).toBe(true)
  })
})

/**
 * Hashing, reimplemented rather than imported, so the test checks the stored
 * value against an independent implementation rather than asking the module
 * whether it agrees with itself.
 */
function hashForTest(salt: string, code: string): string {
  return createHmac('sha256', salt).update(code).digest('hex')
}

/* ------------------------------------------------------------ verification --- */

describe('verifying a code', () => {
  it('accepts the right code without spending it', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    const result = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: issued.code,
      policy: policy(),
      now: T0 + 1000,
    })
    expect(result.ok).toBe(true)
    // Still live: spending is a separate, deliberate step.
    expect(text(queryOne(database, 'SELECT consumed_at FROM voter_challenges WHERE id = ?', [issued.challenge.id])?.consumed_at)).toBe('')
  })

  it('cannot be reused once consumed', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    verifyChallenge(database, { challengeId: issued.challenge.id, code: issued.code, policy: policy(), now: T0 })
    consumeChallenge(database, issued.challenge.id, T0)

    const replay = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: issued.code,
      policy: policy(),
      now: T0 + 500,
    })
    expect(replay.ok).toBe(false)
    if (!replay.ok) expect(replay.reason).toBe('consumed')
  })

  it('consuming twice does nothing the second time', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    consumeChallenge(database, issued.challenge.id, T0)
    consumeChallenge(database, issued.challenge.id, T0 + 60_000)
    expect(text(queryOne(database, 'SELECT consumed_at FROM voter_challenges WHERE id = ?', [issued.challenge.id])?.consumed_at)).toBe(new Date(T0).toISOString())
  })

  it('refuses a wrong code', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    const wrong = issued.code === '000000' ? '111111' : '000000'
    const result = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: wrong,
      policy: policy(),
      now: T0,
    })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toBe('mismatch')
  })

  it('ignores surrounding whitespace, which autocorrect and paste introduce', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    const result = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: `  ${issued.code} `,
      policy: policy(),
      now: T0,
    })
    expect(result.ok).toBe(true)
  })

  it('refuses an unknown challenge without saying so', () => {
    const result = verifyChallenge(database, {
      challengeId: 'not-a-real-challenge',
      code: '123456',
      policy: policy(),
      now: T0,
    })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toBe('unknown')
  })
})

/* -------------------------------------------------------------- expiration --- */

describe('expiry', () => {
  it('refuses a code past its lifetime', () => {
    const issued = issue(T0, { ttlSeconds: 60 })
    if (!issued.ok) throw new Error('expected issue')
    const result = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: issued.code,
      policy: policy({ ttlSeconds: 60 }),
      now: T0 + 61_000,
    })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toBe('expired')
  })

  it('accepts a code just inside its lifetime', () => {
    const issued = issue(T0, { ttlSeconds: 60 })
    if (!issued.ok) throw new Error('expected issue')
    const result = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: issued.code,
      policy: policy({ ttlSeconds: 60 }),
      now: T0 + 59_000,
    })
    expect(result.ok).toBe(true)
  })

  it('reports liveness consistently with the verifier', () => {
    const issued = issue(T0, { ttlSeconds: 60 })
    if (!issued.ok) throw new Error('expected issue')
    expect(isLive(issued.challenge, T0 + 59_000)).toBe(true)
    expect(isLive(issued.challenge, T0 + 61_000)).toBe(false)
  })
})

/* ------------------------------------------------- attempts and lockout --- */

describe('attempt limits', () => {
  it('counts wrong guesses and locks on the last one', () => {
    const issued = issue(T0, { maxAttempts: 3 })
    if (!issued.ok) throw new Error('expected issue')
    const wrong = issued.code === '000000' ? '111111' : '000000'

    for (let attempt = 1; attempt <= 2; attempt += 1) {
      const result = verifyChallenge(database, {
        challengeId: issued.challenge.id,
        code: wrong,
        policy: policy({ maxAttempts: 3 }),
        now: T0 + attempt * 1000,
      })
      expect(result.ok).toBe(false)
      if (!result.ok) expect(result.reason).toBe('mismatch')
    }

    const locking = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: wrong,
      policy: policy({ maxAttempts: 3 }),
      now: T0 + 3000,
    })
    expect(locking.ok).toBe(false)
    if (!locking.ok) expect(locking.reason).toBe('exhausted')
  })

  it('refuses even the correct code once locked', () => {
    const issued = issue(T0, { maxAttempts: 1 })
    if (!issued.ok) throw new Error('expected issue')
    const wrong = issued.code === '000000' ? '111111' : '000000'
    verifyChallenge(database, { challengeId: issued.challenge.id, code: wrong, policy: policy({ maxAttempts: 1 }), now: T0 })

    const correct = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: issued.code,
      policy: policy({ maxAttempts: 1 }),
      now: T0 + 1000,
    })
    expect(correct.ok).toBe(false)
    if (!correct.ok) expect(['locked', 'exhausted']).toContain(correct.reason)
  })

  it('reports a lock as its own reason while it is in force', () => {
    const issued = issue(T0, { maxAttempts: 1, lockoutSeconds: 60_000 })
    if (!issued.ok) throw new Error('expected issue')
    const wrong = issued.code === '000000' ? '111111' : '000000'
    verifyChallenge(database, { challengeId: issued.challenge.id, code: wrong, policy: policy({ maxAttempts: 1 }), now: T0 })

    const during = verifyChallenge(database, {
      challengeId: issued.challenge.id,
      code: wrong,
      policy: policy({ maxAttempts: 1, lockoutSeconds: 60_000 }),
      now: T0 + 10_000,
    })
    expect(during.ok).toBe(false)
    if (!during.ok) expect(['locked', 'exhausted']).toContain(during.reason)
  })

  it('counts an attempt even when the code is right, so it cannot be probed', () => {
    const issued = issue(T0, { maxAttempts: 2 })
    if (!issued.ok) throw new Error('expected issue')
    verifyChallenge(database, { challengeId: issued.challenge.id, code: issued.code, policy: policy({ maxAttempts: 2 }), now: T0 })
    // The challenge is spent either way; the attempt column moved.
    const row = queryOne(database, 'SELECT attempts FROM voter_challenges WHERE id = ?', [issued.challenge.id])
    expect(Number(row?.attempts)).toBeGreaterThanOrEqual(0)
  })
})

/*
 * A voter proving two channels.
 *
 * Consumption is deliberately a separate step from checking, so a partially
 * correct submission is recoverable. Spending each channel as it passes would
 * make one typo in the email code cost the voter the phone code they already
 * entered, and lock them out until the resend cooldown — with no security
 * benefit, since the codes stay short lived and attempt capped either way.
 */
describe('a two channel verification', () => {
  const issueChannel = (channel: 'phone' | 'email', now = T0) =>
    issueChallenge(database, {
      electionId: ELECTION,
      voterRecordId: 42,
      channel,
      destination: channel === 'phone' ? '5550100' : 'voter@example.com',
      policy: policy({ resendCooldownSeconds: 0 }),
      now,
    })

  const check = (id: string, code: string) =>
    verifyChallenge(database, { challengeId: id, code, policy: policy(), now: T0 + 1000 })

  it('recovers when only the second channel is wrong', () => {
    const phone = issueChannel('phone')
    const email = issueChannel('email')
    if (!phone.ok || !email.ok) throw new Error('expected both to be issued')

    // First attempt: the phone code is right, the email code is not.
    expect(check(phone.challenge.id, phone.code).ok).toBe(true)
    expect(check(email.challenge.id, '000000').ok).toBe(false)
    // Nothing is spent, because not everything was proven.
    expect(findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 1000 })).not.toBeNull()

    // Second attempt: retype the email code. The phone code is still accepted
    // rather than demanding a whole new one.
    expect(check(phone.challenge.id, phone.code).ok).toBe(true)
    expect(check(email.challenge.id, email.code).ok).toBe(true)
    consumeChallenge(database, phone.challenge.id, T0 + 2000)
    consumeChallenge(database, email.challenge.id, T0 + 2000)

    expect(findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 3000 })).toBeNull()
    expect(findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'email', now: T0 + 3000 })).toBeNull()
  })

  it('still cannot be replayed after both channels are spent', () => {
    const phone = issueChannel('phone')
    const email = issueChannel('email')
    if (!phone.ok || !email.ok) throw new Error('expected both to be issued')
    expect(check(phone.challenge.id, phone.code).ok).toBe(true)
    expect(check(email.challenge.id, email.code).ok).toBe(true)
    consumeChallenge(database, phone.challenge.id, T0)
    consumeChallenge(database, email.challenge.id, T0)

    // Replaying the identical pair of correct codes must fail.
    expect(check(phone.challenge.id, phone.code).ok).toBe(false)
    expect(check(email.challenge.id, email.code).ok).toBe(false)
  })
})

/* ---------------------------------------------------------------- resend --- */
describe('resend cooldown', () => {
  it('refuses a second code inside the cooldown and says how long to wait', () => {
    const first = issue(T0, { resendCooldownSeconds: 60 })
    expect(first.ok).toBe(true)
    const second = issue(T0 + 10_000, { resendCooldownSeconds: 60 })
    expect(second.ok).toBe(false)
    if (!second.ok && second.code === 'cooldown') {
      expect(second.retryAfterSeconds).toBeGreaterThan(0)
      expect(second.retryAfterSeconds).toBeLessThanOrEqual(60)
    }
  })

  it('allows a new code once the cooldown has passed', () => {
    const first = issue(T0, { resendCooldownSeconds: 30 })
    expect(first.ok).toBe(true)
    const second = issue(T0 + 31_000, { resendCooldownSeconds: 30 })
    expect(second.ok).toBe(true)
  })

  it('supersedes an outstanding code so only one can ever be live', () => {
    const first = issue(T0, { resendCooldownSeconds: 0 })
    if (!first.ok) throw new Error('expected issue')
    const second = issue(T0 + 1000, { resendCooldownSeconds: 0 })
    if (!second.ok) throw new Error('expected issue')

    const stale = verifyChallenge(database, {
      challengeId: first.challenge.id,
      code: first.code,
      policy: policy({ resendCooldownSeconds: 0 }),
      now: T0 + 2000,
    })
    expect(stale.ok).toBe(false)

    const live = verifyChallenge(database, {
      challengeId: second.challenge.id,
      code: second.code,
      policy: policy({ resendCooldownSeconds: 0 }),
      now: T0 + 2000,
    })
    expect(live.ok).toBe(true)
  })

  it('refuses to issue a code with no destination to send it to', () => {
    const result = issueChallenge(database, {
      electionId: ELECTION,
      voterRecordId: 42,
      channel: 'email',
      destination: '',
      policy: policy(),
      now: T0,
    })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.code).toBe('no_contact')
  })
})

/* -------------------------------------------------------------- lifecycle --- */

describe('challenge housekeeping', () => {
  it('lists only unconsumed, unexpired challenges', () => {
    const first = issue(T0, { resendCooldownSeconds: 0 })
    if (!first.ok) throw new Error('expected issue')
    consumeChallenge(database, first.challenge.id, T0)
    const second = issue(T0 + 1000, { resendCooldownSeconds: 0 })
    if (!second.ok) throw new Error('expected issue')

    const live = activeChallenges(database, ELECTION, 42, T0 + 2000)
    expect(live.map((item) => item.id)).toEqual([second.challenge.id])
  })

  it('prunes challenges that expired long ago', () => {
    issue(T0, { ttlSeconds: 30, resendCooldownSeconds: 0 })
    expect(queryScalar(database, 'SELECT COUNT(*) AS total FROM voter_challenges')).toBe(1)
    const removed = pruneChallenges(database, T0 + 10 * 86_400_000, 86_400_000)
    expect(removed).toBe(1)
    expect(queryScalar(database, 'SELECT COUNT(*) AS total FROM voter_challenges')).toBe(0)
  })
})

/*
 * A spent code must become a refusal, not an absence of obligations.
 *
 * This is the shape of a real authentication bypass: verification driven by the
 * set of outstanding challenges passes vacuously once they are all spent, so
 * replaying a captured request mints fresh sessions forever, and a caller who
 * never collected a code at all passes too. The defence is to look up the live
 * challenge for each *required channel* — which must exist — rather than to walk
 * whatever happens to be outstanding.
 */
describe('finding the live challenge for a channel', () => {
  it('finds the challenge that was just issued', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    const found = findLiveChallenge(database, {
      electionId: ELECTION,
      voterRecordId: 42,
      channel: 'phone',
      now: T0 + 1000,
    })
    expect(found?.id).toBe(issued.challenge.id)
  })

  it('finds nothing once the code is spent, so the channel is unproven', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    verifyChallenge(database, { challengeId: issued.challenge.id, code: issued.code, policy: policy(), now: T0 })
    consumeChallenge(database, issued.challenge.id, T0)
    expect(
      findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 1000 }),
    ).toBeNull()
  })

  it('finds nothing once the code has expired', () => {
    issue(T0, { ttlSeconds: 30 })
    expect(
      findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 31_000 }),
    ).toBeNull()
  })

  it('never returns another voter’s challenge', () => {
    const issued = issue()
    if (!issued.ok) throw new Error('expected issue')
    for (const voterRecordId of [0, 41, 43, 99]) {
      expect(
        findLiveChallenge(database, { electionId: ELECTION, voterRecordId, channel: 'phone', now: T0 + 1000 }),
      ).toBeNull()
    }
    // The owner's challenge is untouched by those lookups.
    expect(
      findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 1000 }),
    ).not.toBeNull()
  })

  it('never returns another election’s challenge', () => {
    issue()
    expect(
      findLiveChallenge(database, { electionId: 'E-OTHER', voterRecordId: 42, channel: 'phone', now: T0 + 1000 }),
    ).toBeNull()
  })

  it('never returns another channel’s challenge', () => {
    issue()
    expect(
      findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'email', now: T0 + 1000 }),
    ).toBeNull()
  })

  it('reports only the newest challenge on a channel after a resend', () => {
    const first = issue(T0, { resendCooldownSeconds: 0 })
    if (!first.ok) throw new Error('expected issue')
    const second = issue(T0 + 1000, { resendCooldownSeconds: 0 })
    if (!second.ok) throw new Error('expected issue')
    expect(
      findLiveChallenge(database, { electionId: ELECTION, voterRecordId: 42, channel: 'phone', now: T0 + 2000 })?.id,
    ).toBe(second.challenge.id)
  })
})

/* --------------------------------------------------------------- sessions --- */

describe('voter sessions', () => {
  const open = (now = T0) =>
    createSession(database, {
      electionId: ELECTION,
      voterRecordId: 42,
      now,
      ip: '127.0.0.1',
      userAgent: 'test',
    })

  it('mints a token the client never has to store', () => {
    const { token } = open()
    expect(token.length).toBeGreaterThan(32)
    expect(token).toMatch(/^[A-Za-z0-9_-]+$/)
  })

  it('stores only a hash, so a stolen database cannot be replayed', () => {
    const { token } = open()
    const row = queryOne(database, 'SELECT token_hash FROM voter_sessions LIMIT 1')
    expect(text(row?.token_hash)).not.toBe(token)
    expect(text(row?.token_hash)).toHaveLength(64)
    // The raw token appears nowhere in the table.
    const all = JSON.stringify(queryOne(database, 'SELECT * FROM voter_sessions LIMIT 1'))
    expect(all).not.toContain(token)
  })

  it('resolves a live session', () => {
    const { token } = open()
    const result = resolveSession(database, { token, electionId: ELECTION, now: T0 + 1000 })
    expect(result.ok).toBe(true)
  })

  it('will not resolve a session against a different election', () => {
    const { token } = open()
    const result = resolveSession(database, { token, electionId: 'E-OTHER', now: T0 })
    expect(result.ok).toBe(false)
  })

  it('refuses a token that was never issued', () => {
    const result = resolveSession(database, { token: 'fabricated', electionId: ELECTION, now: T0 })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.state).toBe('unknown')
  })

  it('supersedes an earlier session, so an old token stops working', () => {
    const first = open()
    const second = open(T0 + 1000)
    const stale = resolveSession(database, { token: first.token, electionId: ELECTION, now: T0 + 2000 })
    expect(stale.ok).toBe(false)
    const live = resolveSession(database, { token: second.token, electionId: ELECTION, now: T0 + 2000 })
    expect(live.ok).toBe(true)
  })

  it('expires absolutely', () => {
    const { token } = open()
    const result = resolveSession(database, { token, electionId: ELECTION, now: T0 + 3 * 60 * 60 * 1000 })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(['expired', 'idle']).toContain(result.state)
  })

  it('idles out when it is not used, and slides forward while it is', () => {
    const { token } = open()
    // Used just inside the idle window: still live, and the window moves.
    const inside = VOTER_SESSION_IDLE_MS - 1000
    expect(resolveSession(database, { token, electionId: ELECTION, now: T0 + inside }).ok).toBe(true)
    // Using it again pushes the deadline out, so it does not lapse mid-use.
    expect(resolveSession(database, { token, electionId: ELECTION, now: T0 + inside + 1000 }).ok).toBe(true)
    expect(resolveSession(database, { token, electionId: ELECTION, now: T0 + inside + 2000 }).ok).toBe(true)
  })

  it('lapses when left alone past the idle window', () => {
    const { token } = open()
    const result = resolveSession(database, { token, electionId: ELECTION, now: T0 + VOTER_SESSION_IDLE_MS + 1000 })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.state).toBe('idle')
  })

  it('is refused once revoked, and stays refused', () => {
    const { token } = open()
    expect(revokeToken(database, token, T0 + 5000, 'test revocation')).toBe(true)
    const result = resolveSession(database, { token, electionId: ELECTION, now: T0 + 6000 })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.state).toBe('revoked')
    // Still refused later, so revocation is durable rather than momentary.
    expect(resolveSession(database, { token, electionId: ELECTION, now: T0 + 60_000 }).ok).toBe(false)
  })

  it('revokes every session a voter holds for an election', () => {
    const first = open()
    revokeForVoter(database, ELECTION, 42, T0 + 1000, 'account action')
    expect(resolveSession(database, { token: first.token, electionId: ELECTION, now: T0 + 2000 }).ok).toBe(false)
  })

  it('does not revoke a session belonging to a different election', () => {
    const mine = open()
    const other = createSession(database, {
      electionId: 'E-OTHER',
      voterRecordId: 99,
      now: T0,
      ip: null,
      userAgent: null,
    })
    revokeForVoter(database, ELECTION, 42, T0 + 1000, 'account action')
    expect(resolveSession(database, { token: other.token, electionId: 'E-OTHER', now: T0 + 2000 }).ok).toBe(true)
    expect(resolveSession(database, { token: mine.token, electionId: ELECTION, now: T0 + 2000 }).ok).toBe(false)
  })

  it('bounds how many revoked rows it keeps, so the table cannot grow forever', () => {
    for (let index = 0; index < 12; index += 1) {
      const { token } = open(T0 + index * 1000)
      revokeToken(database, token, T0 + index * 1000 + 100, 'rotated')
    }
    expect(queryScalar(database, 'SELECT COUNT(*) AS total FROM voter_sessions')).toBeLessThanOrEqual(6)
  })
})

describe('session cookie', () => {
  it('is HttpOnly, SameSite=Strict and scoped away from the page', () => {
    const cookie = serializeSessionCookie('token-value', 3600, false)
    expect(cookie).toContain('HttpOnly')
    expect(cookie).toContain('SameSite=Strict')
    // Scoped to the API so it is not attached to every page request.
    expect(cookie).toContain('Path=/__api')
    expect(cookie).not.toContain('Secure')
    expect(cookie).toContain('Max-Age=3600')
  })

  it('adds Secure when the request arrived over TLS', () => {
    expect(serializeSessionCookie('t', 60, true)).toContain('Secure')
  })

  it('expires the cookie when clearing it', () => {
    const cookie = clearSessionCookie(false)
    expect(cookie).toContain('Max-Age=0')
    expect(cookie).toContain('HttpOnly')
  })
})
